### ISSUE TITLE
RIOdroid.sh doesn't install socat correctly

### ISSUE THREAD

**Issue by gbear605** [Spectrum3847/RIOdroid#1]
When it runs `opkg install socat_1.7.2.1-r0_armv7a-vfp-neon.ipk`, it errors with

```
admin@roboRIO-1768-FRC:~# opkg install socat_1.7.2.1-r0_armv7a-vfp-neon.ipk 
Unknown package 'socat'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for socat found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package socat.
```

I am on the most recent version of the roboRIO firmware.

**Comment by allengregoryiv** [comment]
I'm not sure, the easiest solution would be to get your roboRIO connected to the internet and install socat using opkg from the angstrom repo.

**Comment by gbear605** [comment]
That fixed it.

**Comment by Kludgy4** [comment]
I am getting a similar issue
```
opkg install socat_1.7.2.1-r0_armv7a-vfp-neon.ipk
Not selecting socat 1.7.2.1 due to incompatible architecture.
Unknown package 'socat'.
Collected errors:
 * opkg_install_cmd: Cannot install package socat.
```
However the given solution is not helpful to me, and to test whether that would fix the problem I would like some kind of step-by-step (more information), guide on how to connect the roboRIO to the internet, what command to use to "install socat using opkg" etc.

I have attempted connecting the roboRIO to my router via ethernet cable but that does not allow me to ping any websites over SSH

Thank you for the help

**Comment by SpectrumFRC3847** [comment]
You may need to change the architecture file for opkg. We don't use this
and aren't supporting it so if it's broke, we probably won't be fixing it
anymore. The cheesy Poof's have install files that may work better for you.

Allen

**Comment by Kludgy4** [comment]
Thanks for the help :)
